
- name: Create system cron job for log rotation
  cron:
    name: Log rotation for Tuxedo services
    weekday: "*"
    minute: "*/15"
    hour: "*"
    user: "root"
    job: "logrotate {{ tuxedo_log_rotation_config_path }}"
    cron_file: /etc/cron.d/log-rotation

- name: Create maintenance job for periodic mail spool truncation
  cron:
    name: Periodic mail spool truncation
    special_time: weekly
    user: root
    job: truncate -s 0 /var/spool/mail/*
    cron_file: /etc/cron.d/mail-spool

- name: Configure recipient addresses for system cron jobs
  cronvar:
    name: MAILTO
    value: root@localhost
    cron_file: "{{ item }}"
  loop:
    - /etc/crontab
    - /etc/cron.d/clamav-update
    - /etc/cron.d/log-rotation
    - /etc/cron.d/mail-spool
