---

- name: "Set additional variables for template population : {{ tuxedo_service }}"
  ansible.builtin.set_fact:
    orders_min_boot_count: "{{ tuxedo_service_config[tuxedo_service].orders_min_boot_count | default(8) }}"
    private_host_address: "{{ inventory_hostname }}"
    private_host_local_domain_port: "{{ tuxedo_service_config[tuxedo_service].local_domain_port }}"
    service_name: "{{ tuxedo_service }}"
    tuxedo_env_file_path: "/home/{{ tuxedo_service }}/{{ deployment_dir }}/config/envfile"
    tuxedo_orders_env_file_path: "/home/{{ tuxedo_service }}/{{ deployment_dir }}/config/ordersenvfile"
    tuxedo_domain_id: "{{ tuxedo_service | upper }}_{{ 'OIS_' if environment_name == 'live' }}{{ tuxedo_domain_id_suffix }}"
    tuxedo_group_id: "{{ getent_passwd[tuxedo_service][getent_gid_index] }}"
    tuxedo_ipc_key: "{{ tuxedo_service_config[tuxedo_service].ipc_key }}"
    tuxedo_klist_file_path: "/home/{{ tuxedo_service }}/{{ deployment_dir }}/config/klist"
    tuxedo_finance_file_path: "/home/{{ tuxedo_service }}/{{ deployment_dir }}/config/finance"
    tuxedo_local_domain_id: "{{ tuxedo_service | upper }}_{{ 'OIS_' if environment_name == 'live' }}{{ tuxedo_local_domain_suffix }}"
    tuxedo_logical_machine_id: "{{ tuxedo_service | upper }}_{{ 'OIS_' if environment_name == 'live' }}{{ tuxedo_logical_machine_id_suffix }}"
    tuxedo_machine_name: "{{ ansible_facts.hostname }}"
    tuxedo_user_id: "{{ getent_passwd[tuxedo_service][getent_uid_index] }}"
    tuxedo_queue_path: "/home/{{ tuxedo_service }}/queues/{{ tuxedo_queue_space_device }}"
    tuxedo_log_size: "{{ tuxedo_service_config[tuxedo_service].tuxedo_log_size }}"
  no_log: true

- name: "Retrieve alerts config from Hashicorp Vault : {{ tuxedo_service }}"
  ansible.builtin.set_fact:
    alerts_config: "{{ lookup('community.hashi_vault.hashi_vault', alerts.vault_path) }}"
  when: alerts.enabled

- name: "Retrieve stats config from Hashicorp Vault : {{ tuxedo_service }}"
  ansible.builtin.set_fact:
    stats_config: "{{ lookup('community.hashi_vault.hashi_vault', stats.vault_path) }}"
  when: stats.enabled

- name: "Remove maintenance jobs during deploy : {{ tuxedo_service }}"
  ansible.builtin.file:
    path: "/var/spool/cron/{{ tuxedo_service }}"
    state: absent

- name: "Create temporary directory for new deployment : {{ tuxedo_service }}"
  become: true
  become_user: "{{ tuxedo_service }}"
  ansible.builtin.tempfile:
    state: directory
  register: new_deployment_files
  changed_when: true

- name: "Copy application artifact files to temporary deployment directory : {{ tuxedo_service }}"
  become: true
  become_user: "{{ tuxedo_service }}"
  ansible.builtin.command: "cp -r {{ application_artifact_files.path }}/. {{ new_deployment_files.path }}"
  changed_when: true

- name: "Create Tuxedo service logs directory : {{ tuxedo_service }}"
  ansible.builtin.file:
    path: "{{ tuxedo_logs_path }}/{{ tuxedo_service }}"
    owner: "{{ tuxedo_service }}"
    group: "{{ tuxedo_service }}"
    mode: '0755'
    state: directory

- name: "Create config directory : {{ tuxedo_service }}"
  ansible.builtin.file:
    path: "{{ new_deployment_files.path }}/config"
    owner: "{{ tuxedo_service }}"
    group: "{{ tuxedo_service }}"
    mode: '0755'
    state: directory

- name: "Populate Tuxedo template config files : {{ tuxedo_service }}"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ new_deployment_files.path }}/config/{{ item | basename | replace('.j2', '') }}"
    owner: "{{ tuxedo_service }}"
    group: "{{ tuxedo_service }}"
    mode: '0644'
  with_fileglob:
    - "{{ application_configs_path }}/{{ tuxedo_service }}/*.j2"
  no_log: true

- name: "Create scripts directory : {{ tuxedo_service }}"
  ansible.builtin.file:
    path: "{{ new_deployment_files.path }}/scripts"
    owner: "{{ tuxedo_service }}"
    group: "{{ tuxedo_service }}"
    mode: '0755'
    state: directory

- name: "Populate script template files : {{ tuxedo_service }}"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ new_deployment_files.path }}/scripts/{{ item | basename | replace('.j2', '') }}"
    owner: "{{ tuxedo_service }}"
    group: "{{ tuxedo_service }}"
    mode: '0755'
  with_fileglob:
    - "{{ scripts_artifact_path }}/*.j2"

- name: "Set permissions for new deployment files : {{ tuxedo_service }}"
  ansible.builtin.file:
    path: "{{ new_deployment_files.path }}"
    owner: "{{ tuxedo_service }}"
    group: "{{ tuxedo_service }}"
    recurse: true

- name: "Check state of current deployment directory : {{ tuxedo_service }}"
  ansible.builtin.stat:
    path: "/home/{{ tuxedo_service }}/{{ deployment_dir }}"
  register: current_deployment_files

- name: "Stop mncq daemon processes : {{ tuxedo_service }}" # noqa ignore-errors
  become: true
  become_user: "{{ tuxedo_service }}"
  register: stop_mncq_daemon
  ansible.builtin.shell: "source {{ tuxedo_env_file_path }} && /home/{{ tuxedo_service }}/{{ deployment_dir }}/scripts/mncq_stop"
  args:
    executable: /bin/bash
  ignore_errors: true
  when: tuxedo_service != "ceu"
  changed_when: "'mncq daemon stopped' in stop_mncq_daemon.stdout and stop_mncq_daemon.rc == 0"

- name: "Stop packq daemon processes : {{ tuxedo_service }}" # noqa ignore-errors
  become: true
  become_user: "{{ tuxedo_service }}"
  register: stop_packq_daemon
  ansible.builtin.shell: "source {{ tuxedo_env_file_path }} && /home/{{ tuxedo_service }}/{{ deployment_dir }}/scripts/packq_stop"
  args:
    executable: /bin/bash
  ignore_errors: true
  when: tuxedo_service != "ceu" and tuxedo_service != "xml"
  changed_when: "'packq daemon stopped' in stop_packq_daemon.stdout and stop_packq_daemon.rc == 0"

- name: "Stop Tuxedo services : {{ tuxedo_service }}" # noqa ignore-errors
  become: true
  become_user: "{{ tuxedo_service }}"
  ansible.builtin.shell: "source {{ tuxedo_env_file_path }} && timeout -s 9 20 tmshutdown -y"
  args:
    executable: /bin/bash
  ignore_errors: true
  when: current_deployment_files.stat.exists
  changed_when: true

- name: "Clear IPC facilities : {{ tuxedo_service }}"
  become: true
  become_user: "{{ tuxedo_service }}"
  ansible.builtin.shell: "source {{ tuxedo_env_file_path }} && zapipc"
  args:
    executable: /bin/bash
  when: current_deployment_files.stat.exists
  changed_when: true

- name: "Remove rollback directory if present : {{ tuxedo_service }}"
  ansible.builtin.file:
    path: "/home/{{ tuxedo_service }}/{{ rollback_dir }}"
    state: absent

- name: "Backup current deployment directory if one exists : {{ tuxedo_service }}"
  become: true
  become_user: "{{ tuxedo_service }}"
  ansible.builtin.command: "mv /home/{{ tuxedo_service }}/{{ deployment_dir }} /home/{{ tuxedo_service }}/{{ rollback_dir }}"
  when: current_deployment_files.stat.exists
  changed_when: true

- name: "Install new deployment files : {{ tuxedo_service }}"
  become: true
  become_user: "{{ tuxedo_service }}"
  ansible.builtin.command: "mv {{ new_deployment_files.path }} /home/{{ tuxedo_service }}/{{ deployment_dir }}"
  changed_when: true

- name: "Lint Tuxedo ubbconfig file after variable population : {{ tuxedo_service }}"
  become: true
  become_user: "{{ tuxedo_service }}"
  ansible.builtin.shell: "source {{ tuxedo_env_file_path }} && tmloadcf -n ubbconfig"
  args:
    chdir: "/home/{{ tuxedo_service }}/{{ deployment_dir }}/config"
    executable: /bin/bash
  register: ubbconfig_lint
  changed_when: false

- name: "Assert Tuxedo ubbconfig lint success : {{ tuxedo_service }}"
  ansible.builtin.assert:
    that:
      - ubbconfig_lint.rc == 0
    fail_msg: "Tuxedo ubbconfig file failed lint check"
    success_msg: "Tuxedo ubbconfig file passed lint check"

- name: "Generate Tuxedo binary tuxconfig file : {{ tuxedo_service }}"
  become: true
  become_user: "{{ tuxedo_service }}"
  ansible.builtin.shell: "source {{ tuxedo_env_file_path }} && tmloadcf -y ubbconfig"
  args:
    chdir: "/home/{{ tuxedo_service }}/{{ deployment_dir }}/config"
    executable: /bin/bash
  changed_when: true

- name: "Lint Tuxedo dmconfig file after variable population : {{ tuxedo_service }}"
  become: true
  become_user: "{{ tuxedo_service }}"
  ansible.builtin.shell: "source {{ tuxedo_env_file_path }} && dmloadcf -n dmconfig"
  args:
    chdir: "/home/{{ tuxedo_service }}/{{ deployment_dir }}/config"
    executable: /bin/bash
  register: dmconfig_lint
  changed_when: false

- name: "Assert Tuxedo dmconfig lint success : {{ tuxedo_service }}"
  ansible.builtin.assert:
    that:
      - dmconfig_lint.rc == 0
    fail_msg: "Tuxedo dmconfig file failed lint check"
    success_msg: "Tuxedo dmconfig file passed lint check"

- name: "Generate Tuxedo binary bdmconfig file : {{ tuxedo_service }}"
  become: true
  become_user: "{{ tuxedo_service }}"
  ansible.builtin.shell: "source {{ tuxedo_env_file_path }} && dmloadcf -y dmconfig"
  args:
    chdir: "/home/{{ tuxedo_service }}/{{ deployment_dir }}/config"
    executable: /bin/bash
  changed_when: true

- name: "Configure recipient address for user-specific cron job emails : {{ tuxedo_service }}"
  community.general.cronvar:
    name: MAILTO
    value: root@localhost
    user: "{{ tuxedo_service }}"

- name: "Create CloudWatch agent configuration file for Tuxedo service group : {{ tuxedo_service }}"
  ansible.builtin.template:
    src: templates/cloudwatch-config-service.json.j2
    dest: "{{ cloudwatch_agent.config_dir }}/cloudwatch-config-{{ tuxedo_service }}.json"
    owner: cwagent
    group: cwagent
    mode: '0644'
    trim_blocks: false

- name: "Check state of queue : {{ tuxedo_service }}"
  ansible.builtin.stat:
    path: "/home/{{ tuxedo_service }}/queues/{{ tuxedo_queue_space_device }}"
  register: queue

- name: "Create queues directory : {{ tuxedo_service }}"
  ansible.builtin.file:
    path: "/home/{{ tuxedo_service }}/queues"
    state: directory
    mode: '0755'
    owner: "{{ tuxedo_service }}"
    group: "{{ tuxedo_service }}"

- name: "Deploy queue creation script : {{ tuxedo_service }}"
  ansible.builtin.template:
    src: "create_{{ tuxedo_service }}_queue.j2"
    dest: "/home/{{ tuxedo_service }}/create_{{ tuxedo_service }}_queue"
    owner: "{{ tuxedo_service }}"
    group: "{{ tuxedo_service }}"
    mode: '0777'
  when: not queue.stat.exists

- name: "Create universal device entry, queue space, and queues : {{ tuxedo_service }}"
  become: true
  become_user: "{{ tuxedo_service }}"
  ansible.builtin.shell: "source {{ tuxedo_env_file_path }} && ./create_{{ tuxedo_service }}_queue"
  args:
    chdir: "/home/{{ tuxedo_service }}"
    executable: /bin/bash
  when: not queue.stat.exists
  changed_when: true

- name: "Remove queue creation script : {{ tuxedo_service }}"
  ansible.builtin.file:
    path: "/home/{{ tuxedo_service }}/create_{{ tuxedo_service }}_queue"
    state: absent
  when: not queue.stat.exists

- name: "Start Tuxedo services : {{ tuxedo_service }}"
  become: true
  become_user: "{{ tuxedo_service }}"
  ansible.builtin.shell: "source {{ tuxedo_env_file_path }} && tmboot -y"
  args:
    executable: /bin/bash
  changed_when: true

- name: "Start mncq daemon processes : {{ tuxedo_service }}" # noqa ignore-errors
  become: true
  become_user: "{{ tuxedo_service }}"
  register: start_mncq_daemon
  ansible.builtin.shell: "source {{ tuxedo_env_file_path }} && /home/{{ tuxedo_service }}/{{ deployment_dir }}/scripts/mncq_start"
  args:
    executable: /bin/bash
  ignore_errors: true
  when: tuxedo_service != "ceu"
  changed_when: "start_mncq_daemon.rc == 0"

- name: "Start packq daemon processes : {{ tuxedo_service }}"
  become: true
  become_user: "{{ tuxedo_service }}"
  register: start_packq_daemon
  ansible.builtin.shell: "source {{ tuxedo_env_file_path }} && /home/{{ tuxedo_service }}/{{ deployment_dir }}/scripts/packq_start"
  args:
    executable: /bin/bash
  ignore_errors: true
  when: tuxedo_service != "ceu" and tuxedo_service != "xml"
  changed_when: "start_packq_daemon.rc == 0"

- name: "Create maintenance jobs : {{ tuxedo_service }}"
  ansible.builtin.cron:
    name: "{{ item.name }}"
    day: "{{ item.day_of_month }}"
    weekday: "{{ item.day_of_week }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    month: "{{ item.month }}"
    user: "{{ tuxedo_service }}"
    job: "source {{ tuxedo_env_file_path }} && /home/{{ tuxedo_service }}/{{ deployment_dir }}/scripts/{{ item.script }}"
    disabled: "{{ item.disabled | default(false) }}"
  loop: "{{ maintenance_jobs[tuxedo_service] | default([]) }}"
