
---

- name: Install mailx mail processing system
  yum:
    name: mailx
    state: present

- name: Configure mailx SMTP relay
  lineinfile:
    path: /etc/mail.rc
    regexp: '^set smtp='
    line: 'set smtp={{ smtp_mail_relay }}'
