---

roles:
  - src: https://github.com/companieshouse/ansible-role-nfs-mounts
    name: nfs-mounts
    version: "1.1.0"

collections:
  - name: amazon.aws
    version: "8.1.0"
  - name: community.general
    version: "9.3.0"
  - name: companieshouse.general
    version: "1.0.1"
